### PR TITLE
Update core.py

### PR DESCRIPTION
**Pull request by shakasaki**
use a minimum chain length calculated from all chains

### CODE REVIEW

**Comment by michaelosthege** [comment]
Did you close it on purpose?

I'm thinking about introducing a `equalize_chain_lengths=True/False` option with `True` as the default.

Will do this some time today once I get the chance.

**Comment by shakasaki** [comment]
oops sorry, didn't do this on purpose! Yes, its probably better to introduce a boolean flag for this!

**Comment by michaelosthege** [comment]
Okay, so as far as I understand you're "unblocked" right now so there's no immediate time pressure, right?

If you can spend some time (sounds like your model is going to run for a few weeks now 😄) you're welcome to implement the boolean flag :)

Otherwise, as I said, I'll get it done within the next 3 days.

**Comment by michaelosthege** [comment]
This got replaced by #46

**Pull request closed without merging**
