### PR TITLE
Remove setuptools workaround

### PR DESCRIPTION
**Pull request by maresb**
## Do not merge...

until https://github.com/aesara-devs/aesara/pull/1100 and https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/307 are also merged.

### CODE REVIEW

**Comment by maresb** [comment]
I seem to have recent acquired the habit of reverting your changes. :laughing:

**Comment by michaelosthege** [comment]
> I seem to have recent acquired the habit of reverting your changes. 😆

That's okay 😅 Thanks for opening the PR - I already forgot about this...

By the way, today I realized that PyMC is still on an "outdated" Aesara version and the import fixes have not yet arrived for our main branch..

**Comment by maresb** [comment]
Hmm, am I missing something, or are you looking at an old commit?

Aesara is at 2.7.9:
image

PyMC is on Aesara 2.7.9:
image

The upstream fix https://github.com/aesara-devs/aesara/pull/1050 was merged in Aesara [v2.7.8](https://github.com/aesara-devs/aesara/releases/tag/rel-2.7.8)

So it seems to me like PyMC is fine, no?

**Comment by maresb** [comment]
Ah... do you mean that `mcbackend` is on an old `pymc` version which, when installed with PyPI would not incorporate https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/307, and thus still be vulnerable to the issue?

Indeed one should probably wait until both PyMC and Aesara have new releases before merging this.

**Comment by michaelosthege** [comment]
You're right, I'm mixing up two different things here.
I will merge this PR because the setuptools things is indeed fixed.

I was concerned about the import mess, which I just confirmed is still happening with Aesara 2.7.9 👇

image

**Review by michaelosthege — APPROVED** [review]

**Comment by maresb** [comment]
Oh no!!! :disappointed: 

Which commands did you use to install?

**Comment by maresb** [comment]
Thanks for the merge at PyMC.

Does the following logic seem correct?

In the screenshot above, you're running pymc 4.1.4, but since it didn't exist on conda-forge (and won't exist until the CDN updates), it couldn't have been installed from the `pymc` CF package, so it's not surprising that g++ is broken.

**Comment by michaelosthege** [comment]
Nevermind, I created several envs with Python 3.9, 3.10 and PyMC 4.1.2, 4.1.3 and 4.1.4 and none of the new environments had the issue.

`mamba create -n pmtest412 -c conda-forge "python==3.9" "pymc==4.1.2"`

After running `mamba install -c conda-forge "pymc==4.1.4"` in the environment that produced the screenshot above, also there the problems magicly went away.

**Comment by maresb** [comment]
:sweat_smile: Great!!!

**Pull request merged**
